#!/bin/bash

[[ -d ~/.vim ]] && rm -rf ~/.vim

ln -sfT .config/dotfiles/inputrc ~/.inputrc
ln -sfT .config/dotfiles/bashrc ~/.bashrc
ln -sfT .config/dotfiles/jshintrc ~/.jshintrc
ln -sfT .config/dotfiles/gitconfig ~/.gitconfig
ln -sfT .config/dotfiles/tmux.conf ~/.tmux.conf
ln -sfT .config/dotfiles/vim ~/.vim
ln -sfT dotfiles/vim ~/.config/nvim

VIM=$(which 2>/dev/null vim) || VIM=$(which 2>/dev/null nvim) || exit 0
$VIM +PlugClean! +PlugUpdate +qall
