#!/bin/bash

[[ -d ~/.vim ]] && rm -rf ~/.vim

ln -sfT .config/dotfiles/inputrc ~/.inputrc
ln -sfT .config/dotfiles/bashrc ~/.bashrc
ln -sfT .config/dotfiles/jshintrc ~/.jshintrc
ln -sfT .config/dotfiles/gitconfig ~/.gitconfig
ln -sfT .config/dotfiles/tmux.conf ~/.tmux.conf
ln -sfT .config/dotfiles/vim ~/.vim
ln -sfT dotfiles/nvim ~/.config/nvim
ln -sfT dotfiles/alacritty ~/.config/alacritty

if command -v >/dev/null vim; then
  vim -es -u ~/.config/dotfiles/vim/vimrc -i NONE -c PlugInstall -c qa
fi

if command -v >/dev/null nvim; then
  repo=https://github.com/wbthomason/packer.nvim
  install_path=~/.local/share/nvim/site/pack/packer/start/packer.nvim
  if [[ -e $install_path ]] || git clone --depth 1 $repo $install_path; then
    nvim --headless -u .config/nvim/lua/plugins.lua -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
  fi
fi
